feat: swap to qtpy and support pyside6
aws-deadline/deadline-cloud-for-keyshot pull request #78
Opened 2024-05-10 22:36 UTC by lucaseck

### What was the problem/requirement? (What/Why)
We were locked to just Pyside2 support which limited the submitter to only being able to run with Python < 3.11.
### What was the solution? (How)
Use qtpy instead so that Pyside2 can still be used, or Pyside6, or any other Qt package.
### What is the impact of this change?
More flexability and Pyside6 can now be used(`pip install deadline[gui]` brings in pyside6-essentials)
### How was this change tested?
Ran the submitter using both Pyside2 and Pyside6 to submit a job
### Was this change documented?
No
### Is this a breaking change?
No
----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-05-10 22:38 UTC, epmog requested changes

2024-05-10 22:38 UTC, epmog commented on README.md
> +    - e.g. `pip install deadline deadline[gui]`
```suggestion
    - e.g. `pip install "deadline[gui]"`
```

2024-05-10 22:40 UTC, epmog approved these changes

2024-05-11 03:06 UTC, crowecawcaw approved these changes

2024-05-13 14:36 UTC, merged